### ISSUE TITLE
XML source fails validation

### ISSUE THREAD

**Issue by reschke** [ietf-wg-httpapi/linkset#10]
xmllint --valid says:

> error : Unknown IO error
> draft-ietf-httpapi-linkset-02.xml:26: warning: failed to load external entity "http://xml.resource.org/authoring/rfc2629.dtd"
> ]>
>  ^

Simply removing 'SYSTEM "http://xml.resource.org/authoring/rfc2629.dtd"' seems to fix that.

**Comment by dret** [comment]
that seems to be a connectivity problem on your side, @reschke. validating with my local tool succeeds, and http://xml.resource.org/authoring/rfc2629.dtd seems to be working just fine. maybe try again?

**Comment by reschke** [comment]
No, reproducably.

One issue is that that resource redirects twice (to "https://xml2rfc.tools.ietf.org/authoring/rfc2629.dtd"). Redirects that move from http to https are not alway followed (thus I het an error with Saxon/J). Changing the URI to the redirect target fixes that.

xmllint however continues to fail for me. Maybe it has problems with https?:

> xmllint: using libxml version 20910
>  compiled with: Threads Tree Output Push Reader Patterns Writer SAXv1 FTP HTTP DTDValid HTML Legacy C14N Catalog XPath XPointer XInclude Iconv ISO8859X Unicode Regexps Automata Schemas Schematron Modules Debug Zlib Lzma

-> <https://gitlab.gnome.org/GNOME/libxml2/-/issues/160>

FWIW; I don't really get why you want to reference the DTD (or even still use xml2rfc v2). But in anycase, fixing the URI to the redirect tatget would help.

**Comment by dret** [comment]
On 2021-06-01 11:31, Julian Reschke wrote:
> FWIW; I don't really get why you want to reference the DTD (or even 
> still use xml2rfc v2).

it's an old draft; we started with v2 quite a while ago...

> But in anycase, fixing the URI to the redirect tatget would help.

ok, it's fixed. thanks for the feedback!

**Comment by reschke** [comment]
> it's an old draft; we started with v2 quite a while ago...

You may want to switch to v3 so you can actually use non-ASCII characters in the examples...

**Comment by dret** [comment]
On 2021-06-01 12:25, Julian Reschke wrote:
>     it's an old draft; we started with v2 quite a while ago...
> 
> You may want to switch to v3 so you can actually use non-ASCII 
> characters in the examples...

that's some motivation but not really critical for us. i'll definitely 
make sure to use v3 for any new drafts.

**Comment by dret** [comment]
if avoiding the HTTP redirects worked well enough, @reschke, i guess we can close this issue?

**Comment by reschke** [comment]
It works for me now, but I still don't get why you want the DTD reference at all.

**Comment by dret** [comment]
On 2021-06-01 16:26, Julian Reschke wrote:
> It works for me now, but I still don't get why you want the DTD 
> reference at all.

it supports tools that simply access the external DTD to validate the 
XML. if it works, i think we're good for now.

**Comment by reschke** [comment]
Validating against a DTD specified by the document is pointless.

What's relevant is validating against the DTD the tool *expects*. xml2rfc will default to it's DTD version in any case.

**Comment by dret** [comment]
On 2021-06-01 16:50, Julian Reschke wrote:
> Validating against a DTD specified by the document is pointless.

unless you're using a generic XML tool and you're ok with doing this.

> What's relevant is validating against the DTD the tool /expects/. 
> xml2rfc will default to it's DTD version in any case.

that's fine as well, of course. if your tooling works now and my tooling 
continues to work, i think we've reached an ideal point to close this 
issue.
