### ISSUE TITLE
reference current http-core drafts instead of RFC 7230/7231

### ISSUE THREAD

**Issue by reschke** [ietf-wg-httpapi/linkset#11]

**Comment by dret** [comment]
i am wondering if referencing drafts doesn't automatically hold up this 
draft from progressing until the references are stable RFCs? not sure 
what the official policy is, but at least so far my personal strategy 
has been to only reference drafts when there's no existing stable reference.

**Comment by reschke** [comment]
The http-core drafts are in IETF Last Call. They do change terminology a bit from RFC 723x, and you'll have to update at some point in the future anyway (unless you manage to beat those drafts in getting into the RFC Publication Queue).

**Comment by dret** [comment]
On 2021-06-01 14:54, Julian Reschke wrote:
> The http-core drafts are in IETF Last Call. They do change terminology a 
> bit from RFC 723x, and you'll have to update at some point in the future 
> anyway (unless you manage to beat those drafts in getting into the RFC 
> Publication Queue).

fair point. i'll leave this issue open for now, but i think it can be 
considered editorial.
