### ISSUE TITLE
reference entries are missing for RFC 6906 an 7284

### ISSUE THREAD

**Issue by reschke** [ietf-wg-httpapi/linkset#12]

**Comment by dret** [comment]
good catch, thanks. should be fixed now.

**Comment by reschke** [comment]
Still broken. You'll have to properly name the entities.

**Comment by dret** [comment]
On 2021-06-01 16:25, Julian Reschke wrote:
> Still broken. You'll have to properly name the entities.

that quick fix was a bit too quick... thanks for double-checking!

**Comment by dret** [comment]
generated new versions and the references are now in there: https://github.com/ietf-wg-httpapi/linkset/blob/master/draft-ietf-httpapi-linkset-02.txt
