### ISSUE TITLE
Terminology: "Absolute URI" doesn't mean what one may think it means

### ISSUE THREAD

**Issue by dret** [ietf-wg-httpapi/linkset#17]
https://datatracker.ietf.org/doc/html/rfc3986#section-4.3 defines "absolute URI" to mean one that is non-relative and has no fragment identifier. currently, the draft uses the term in a more colloquial way in the sense of "non-relative URI". this should be clarified so that the language of the draft and RFC 3986 are aligned.

**Comment by awwright** [comment]
May I suggest: 

In JSON Schema, if simply "URI" would be ambiguous in context, we say "full URI" or even "full URI (with a scheme)".

There's one case where we refer to the `absolute-URI` production, so we say "absolute-URI (with a scheme, but no fragment)"

**Comment by dret** [comment]
thanks for your suggestion, austin.

On 2021-06-20 10:11, Austin Wright wrote:
> May I suggest:
> 
> In JSON Schema, if simply "URI" would be ambiguous in context, we say 
> "full URI" or even "full URI (with a scheme)".

interesting. i guess you can say whatever you like and have to define 
somewhere anyway what you mean by saying it. to me, "non-relative" is a 
bit more descriptive, but maybe we have others leaning in one direction 
or the other?

> There's one case where we refer to the |absolute-URI| production, so we 
> say "absolute-URI (with a scheme, but no fragment)"

that's a reference that we are not making.

-- 
erik wilde | ***@***.*** |
            | http://dret.net/netdret    |
            | http://twitter.com/dret    |

**Comment by philarcher** [comment]
It was a surprise to me to learn that Absolute URI means what it clearly does mean - I've always taken it to mean non-relative. I'm tempted to say that in the Linkset spec should state that within the document 'Absolute URI' means non-relative but we recognize that formally the term also precludes any fragment - and then carry on using Absolute URI. That's probably very un-communitaire of me but I have an idea only purists would be upset??

**Comment by dret** [comment]
looks good to me, thanks for making the changes, @hvdsomp!
