### ISSUE TITLE
HTTP Link header field encoding

### ISSUE THREAD

**Issue by reschke** [ietf-wg-httpapi/linkset#20]
> Whereas the HTTP "Link" Header field depends on HTTP and hence on [RFC0822] for its encoding, (...)

This is misleading. HTTP has no normative dependency on RFC 822. Maybe just state that non-ASCII in HTTP field values is not interoperable.

> ... the format specified here is encoded as UTF-8 [RFC3629].

While I sympathize with that choice, what does it actually mean, if the syntax from the HTTP field is re-used anyway?

**Comment by hvdsomp** [comment]
Closing this as it was addressed in a manner aligned with @reschke's suggestion
