### ISSUE TITLE
4.2.2. Link Context Object: is "anchor" required?

### ISSUE THREAD

**Issue by reschke** [ietf-wg-httpapi/linkset#21]
> Each link context object MAY have an "anchor" member with a value that represents the link context. If present, this value SHOULD be an absolute URI as defined in Section 4.3 of [RFC3986]. Cases where the anchor member is present, but no value is provided for it (i.e. the resource providing the set of links is the link context for each link in the link context object) MUST be handled by providing an "anchor" member with empty string ("anchor": "").

The first MAY makes the anchor optional. Why then require it to be present with possible empty value in the last sentence?

**Comment by hvdsomp** [comment]
On Jun 22, 2021, at 21:00, Julian Reschke ***@***.***> wrote:
> 
> ﻿
> Each link context object MAY have an "anchor" member with a value that represents the link context. If present, this value SHOULD be an absolute URI as defined in Section 4.3 of [RFC3986]. Cases where the anchor member is present, but no value is provided for it (i.e. the resource providing the set of links is the link context for each link in the link context object) MUST be handled by providing an "anchor" member with empty string ("anchor": "").
> 
> The first MAY makes the anchor optional. Why then require it to be present with possible empty value in the last sentence?
> 

That’s not what the sentence does. The sentence says what to do in case one is going to go out of their way to provide the optional anchor but somehow is too lazy to stuff an actual URI in it. 

H

**Comment by reschke** [comment]
Ok, but it is confusing. Providing an empty string is a violation of the "SHOULD be an absolute URI".

**Comment by hvdsomp** [comment]
On Jun 22, 2021, at 23:03, Julian Reschke ***@***.***> wrote:
> Ok, but it is confusing. Providing an empty string is a violation of the "SHOULD be an absolute URI".
> 

I’m really not getting that. If the spec would say “MUST be an absolute URI”, then I would clearly see the violation. With a SHOULD, I just don’t see it. 

H

**Comment by reschke** [comment]
> 3. SHOULD   This word, or the adjective "RECOMMENDED", mean that there
   may exist valid reasons in particular circumstances to ignore a
   particular item, but the full implications must be understood and
   carefully weighed before choosing a different course.

So what would be these "valid reasons" not to just skip the "anchor" member?

**Comment by hvdsomp** [comment]
On Jun 22, 2021, at 23:25, Julian Reschke ***@***.***> wrote:
> 
> SHOULD This word, or the adjective "RECOMMENDED", mean that there
> may exist valid reasons in particular circumstances to ignore a
> particular item, but the full implications must be understood and
> carefully weighed before choosing a different course.
> So what would be these "valid reasons" not to just skip the "anchor" member?
> 
4+ year history hunting us. And clearly it’s not over yet. 

So, how about:
- optional anchor
- if anchor is provided it must be an absolute uri

H

**Comment by hvdsomp** [comment]
Actually, it just occurred to me we can't require an absolute URI. we can require a URI though. So, this would become:

- anchor is optional
- if anchor is provided, its value must be a URI

**Comment by dret** [comment]
On 2021-06-23 11:08, Herbert Van de Sompel wrote:
> Actually, it just occurred to me we can't require an absolute URI. we 
> can require a URI though. So, this would become:
> 
>   * anchor is optional
>   * if anchor is provided, its value must be a URI

isn't that a discussion we've had before and where we at some point 
decided that we don't want to constrain what RFC 8288 allows? meaning 
that we'd recommend using "absolute URIs" but wouldn't require them?

**Comment by hvdsomp** [comment]
Indeed. That's why I rephrased my original proposal by changing the "absolute URI" to just "URI".

**Comment by reschke** [comment]
AFAICT, RFC 8288 uses URI-Reference (https://greenbytes.de/tech/webdav/rfc3986.html#uri-reference); any reason to deviate from that?

**Comment by hvdsomp** [comment]
Closing this as it was addressed in a manner aligned with #17, which was also closed.
