### ISSUE TITLE
profile-based conneg?

### ISSUE THREAD

**Issue by reschke** [ietf-wg-httpapi/linkset#23]
5. The "profile" attribute for media types to Represent Sets of Links

> The profile parameter MAY be used by clients to express their preferences, and, if a client does so, a server SHOULD return a document that honors the profiles it recognizes, and MUST ignore the profiles which it does not recognize.

Is this about HTTP content negotiation? In that case linking to the specific part of the HTTP spec might be helpful.

**Comment by hvdsomp** [comment]
On Jun 22, 2021, at 21:20, Julian Reschke ***@***.***> wrote:
> 
> ﻿
> The "profile" attribute for media types to Represent Sets of Links
> The profile parameter MAY be used by clients to express their preferences, and, if a client does so, a server SHOULD return a document that honors the profiles it recognizes, and MUST ignore the profiles which it does not recognize.
> 
> Is this about HTTP content negotiation? In that case linking to the specific part of the HTTP spec might be helpful.
> 

I don’t think this is about content negotiation because AFAIK Profile negotiation isn’t standardized yet. Although there’s attempts, see https://datatracker.ietf.org/doc/draft-svensson-profiled-representations/

 So, this is just about expressing profiles for the benefit of clients. 

H

**Comment by reschke** [comment]
> So, this is just about expressing profiles for the benefit of clients. 

So if it's not about HTTP connect, what is it about? Concrete example?

**Comment by hvdsomp** [comment]
On Jun 22, 2021, at 23:00, Julian Reschke ***@***.***> wrote:
> 
> ﻿So, this is just about expressing profiles for the benefit of clients.
> So if it's not about HTTP connect, what is it about? Concrete example?
> 
From Section 5:

For example, the attribute could be used
   to indicate that a link set uses a specific, limited set of link
   relation types.
H

**Comment by reschke** [comment]
That's the server using it. But the spec says:

> The profile parameter MAY be used by clients to express their preferences (...)

What's an example use by a *client*?

**Comment by hvdsomp** [comment]
On Jun 22, 2021, at 23:27, Julian Reschke ***@***.***> wrote:
> 
> That's the server using it. But the spec says:
> The profile parameter MAY be used by clients to express their preferences (...)
> 
> What's an example use by a client?
> 

Oh, now I get it. It’s about this:

The profile parameter MAY be used by clients to express their
   preferences, and, if a client does so, a server SHOULD return a
   document that honors the profiles it recognizes, and MUST ignore the
   profiles which it does not recognize.
I tend to agree that it could be appropriate to leave this part out and leave this aspect to potentially forthcoming profile negotiation guidelines. 

H

**Comment by hvdsomp** [comment]
Closing this as it was addressed by removing the sentence that suggested negotiation.
