### ISSUE TITLE
resolving non-absolute URIs

### ISSUE THREAD

**Issue by reschke** [ietf-wg-httpapi/linkset#24]
6. The "linkset" Relation Type for Linking to a Set of Links

> A user agent that follows a "linkset" link and obtains links for which anchors and targets are not expressed as absolute URIs MUST properly determine what the context is for these links (...)

Would be good to actually state what the proper way to determine the context is.

**Comment by dret** [comment]
maybe simply remove "properly" because we cannot say what the "proper" way is. but we want to make it explicit that it is important to resolve relative URIs against whatever the context of the linkset is.

**Comment by dret** [comment]
thanks for making that change, @hvdsomp, and since @reschke signaled that he's ok with it, i am closing this issue.
