### ISSUE TITLE
broken Link header fields

### ISSUE THREAD

**Issue by reschke** [ietf-wg-httpapi/linkset#26]
There are examples of the type:

~~~
Link: <https://example.org/links/resource1> ; rel="alternate" 
; type="application/linkset+json"
~~~

Note that whitespace would be needed in the continuation line.

**Comment by hvdsomp** [comment]
On Jun 22, 2021, at 21:27, Julian Reschke ***@***.***> wrote:
> There are examples of the type:
> 
> Link: <https://example.org/links/resource1> ; rel="alternate" 
> ; type="application/linkset+json"
> Note that whitespace would be needed in the continuation line.
> 

From the Terminology section:

In the examples provided in this document, links in the HTTP "Link"
   header are shown on separate lines in order to improve readability.
   Note, however, that as per Section 3.2 of [RFC7230], line breaks are
   not allowed in values for HTTP headers; only whitespaces and tabs are
   supported as seperators.

**Comment by reschke** [comment]
Yes, I know that.

But what you currently use is not an HTTP message. You can fix it by adding leading whitespace.

**Comment by dret** [comment]
sounds like an easy fix. i'll have a look and if we change the example(s) it seems we can also remove the cautionary note in the terminology section?

**Comment by hvdsomp** [comment]
Personally, I would prefer handling all examples in the way it's done in Figure 12 (see below) and keep the cautionary note. I think that approach really helps for legibility.

```
HTTP/1.1 200 OK
Date: Mon, 12 Aug 2019 10:45:54 GMT
Server: Apache-Coyote/1.1
Link: <https://example.org/links/resource1>
         ; rel="linkset"
         ; type="application/linkset+json"
Content-Length: 236
Content-Type: text/html;charset=utf-8
```

**Comment by dret** [comment]
my guess is @reschke refers to this example:

```
Link: <https://example.org/links/resource1> ; rel="alternate" 
; type="application/linkset+json"
```

(and a second one like it) which indeed seem to be in need of fixing.

**Comment by dret** [comment]
On 2021-06-23 10:28, Herbert Van de Sompel wrote:
> Personally, I would prefer handling all examples in the way it's done in 
> Figure 12 (see below) and keep the cautionary note. I think that 
> approach really helps for legibility.

ok, this is done and if everybody is happy then maybe we can close this 
issue?

**Comment by reschke** [comment]
Yes, this issue is addressed.

Note that

> line breaks are not allowed in values for HTTP headers

is a bit misleading; "deprecated" would be more precise.

**Comment by dret** [comment]
assuming that we have no fully addressed this issue, i am closing it. thanks, @reschke!
