### ISSUE TITLE
Implementation Status

### ISSUE THREAD

**Issue by reschke** [ietf-wg-httpapi/linkset#28]
please move to an appendix

**Comment by dret** [comment]
On 2021-06-22 21:32, Julian Reschke wrote:
> please move to an appendix

no worries. as indicated in the first paragraph, this whole section is 
just for the draft and will be removed for the final publication.

**Comment by reschke** [comment]
Yes, but that means that paragraph numbers of subsequent sections will change during the publication process. That's why it's a good idea to move stuff that is going to be removed to the end.

**Comment by hvdsomp** [comment]
On Jun 22, 2021, at 21:41, Julian Reschke ***@***.***> wrote:
> 
> ﻿
> Yes, but that means that paragraph numbers of subsequent sections will change during the publication process. That's why it's a good idea to move stuff that is going to be removed to the end.
> 
I’ve published numerous documents in a variety of venues over the past 30 years and this is a concern I have not encountered before. It’s also the first time I see this suggestion in relation to the IETF publication process. Did we miss a new guideline with this regard?

H

**Comment by dret** [comment]
closing since the section was moved to an appendix as requested.
