### ISSUE TITLE
Interop considerations

### ISSUE THREAD

**Issue by reschke** [ietf-wg-httpapi/linkset#29]
> Interoperability considerations: The interoperability considerations of [I-D.ietf-httpbis-semantics] apply.

This makes it sound as if the HTTP spec has a section talking specifically about interop. That is not true.

**Comment by dret** [comment]
i am tempted to change this to "N/A" because that's what https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-messaging-16#section-10.1 uses for their "Interoperability considerations" in the media type registrations.

**Comment by dret** [comment]
closing this one because @reschke indicated that he would be ok with the proposed resolution.
