### ISSUE TITLE
IANA considerations

### ISSUE THREAD

**Issue by reschke** [ietf-wg-httpapi/linkset#30]
> The link relation type below has been registered by IANA

Actually, it has to be registered. Please do not confuse IANA :-)

**Comment by dret** [comment]
On 2021-06-22 21:36, Julian Reschke wrote:
>     The link relation type below has been registered by IANA
> 
> Actually, it has to be registered. Please do not confuse IANA :-)

so far, this language has always worked fine and when it shows up in the 
final RFC, that's the message we want to convey.

**Comment by hvdsomp** [comment]
On Jun 22, 2021, at 21:48, Erik Wilde ***@***.***> wrote:
> On 2021-06-22 21:36, Julian Reschke wrote:
> > The link relation type below has been registered by IANA
> > 
> > Actually, it has to be registered. Please do not confuse IANA :-)
> 

https://github.com/protocol-registries/link-relations/issues/23

Herbert

**Comment by reschke** [comment]
> so far, this language has always worked fine and when it shows up in the
final RFC, that's the message we want to convey.

"IANA Considerations", prior to publication, are instructions to IANA what should be done upon approval.

**Comment by dret** [comment]
is there a real possibility for confusing IANA here or a risk of the final text not being as it should be? if not, can we please close this issue?

**Comment by reschke** [comment]
You can ignore the issue, but I'm 99% sure it will come up again during LC, IESG review, or IANA review.

**Comment by dret** [comment]
On 2021-06-23 09:13, Julian Reschke wrote:
> You can ignore the issue, but I'm 99% sure it will come up again during 
> LC, IESG review, or IANA review.

that would be a new policy since that's the language i've always used 
and it was never brought up in any shape or form. thanks for the heads 
up and let's just wait and see what happens.

-- 
erik wilde | ***@***.*** |
            | http://dret.net/netdret    |
            | http://twitter.com/dret    |

**Comment by reschke** [comment]
FWIW: https://www.ietf.org/rfcdiff?url1=draft-wilde-sunset-header-11.txt&url2=rfc8594

**Comment by richsalz** [comment]
As chair:  please follow the common construction.
- Have an IANA considerations section
- Write things as "IANA is requested to ..." and then details

Other things might have worked before, but consistency is more important.

**Comment by dret** [comment]
On 2021-06-23 15:07, Rich Salz wrote:
> As chair: please follow the common construction.
> 
>   * Have an IANA considerations section
>   * Write things as "IANA is requested to ..." and then details
> 
> Other things might have worked before, but consistency is more important.

ok, thanks for the guidance. here you go.

https://github.com/ietf-wg-httpapi/linkset/commit/250db344e150fb75f93d4f736213dcac7d8776fa

**Comment by dret** [comment]
i think this can be closed since the language has been adjusted as requested.
