### ISSUE TITLE
Stand alone resources

### ISSUE THREAD

**Issue by philarcher** [ietf-wg-httpapi/linkset#35]
The current abstract text says "This specification defines two document formats and respective media types for representing sets of links as stand-alone resources."

MNot's comment on this (https://mailarchive.ietf.org/arch/msg/httpapi/gv9uqyD8Fv96P-_ip9LWIiCqALM/) is "This doesn't agree with the HTTP definition of 'resource'; recommend dropping this phrase."

Personally, I am against this change. If the context is an absolute URI then a Linkset *is* a stand alone resource, surely?

**Comment by richsalz** [comment]
Is it perhaps a "sub-resource"  I agree that an HTTP resource has a URI/URL.

**Comment by dret** [comment]
we will most likely say "document" instead.

**Comment by hvdsomp** [comment]
The proposal is to change the sentence:

This specification defines two document formats and respective media types for representing sets of links as stand-alone resources.

To:

This specification defines two formats and respective media types for representing sets of links as stand-alone documents.

@mnot, please let us know if not OK.

**Comment by mnot** [comment]
That's better, but that's like of like saying "JSON is a format with a media type for representing data structures as stand-alone documents" -- the phrase _as stand-alone documents_ is redundant.

**Comment by dret** [comment]
On 2021-09-23 02:39, Mark Nottingham wrote:
> That's better, but that's like of like saying "JSON is a format with a 
> media type for representing data structures as stand-alone documents" -- 
> the phrase /as stand-alone documents/ is redundant.

that's technically true, but here we're having something that used to be 
*not* standalone in its previous form, and making it so was the main 
motivation for this work. can you live with that redundancy, @mnot?

**Comment by mnot** [comment]
Oh sure - just giving editorial feedback at this point.

**Comment by philarcher** [comment]
If the consensus is that document is more appropriate here than resource then, well, OK!

**Comment by hvdsomp** [comment]
Closing as a result of above commit.
