### ISSUE TITLE
Include word serialization in intro

### ISSUE THREAD

**Issue by philarcher** [ietf-wg-httpapi/linkset#36]
Answering MNot's second comment at https://mailarchive.ietf.org/arch/msg/httpapi/gv9uqyD8Fv96P-_ip9LWIiCqALM/

I suggest the  1st sentence of the second paragraph of the intro could be:

"Therefore, this specification defines two document formats that serialize Web Links and their attributes, and associated media types to represent sets of links...  "

**Comment by philarcher** [comment]
Actually, given Mark's third comment, how about:

"Therefore, this specification defines two document formats that serialize Web Links and their attributes. One serializes links in the same format as used in HTTP the Link header, and the other as a JSON object. It also defines associated media types to represent sets of links and the "linkset" relation type that supports discovery of any resource that conveys a set of links as a stand-alone document.

**Comment by hvdsomp** [comment]
The proposal is to replace the sentence:

Therefore, this specification defines two document formats and associated media types to represent sets of links. It also defines the "linkset" relation type that supports discovery of any resource that conveys a set of links as a stand-alone document.

By the one suggested by @philarcher:

Therefore, this specification defines two document formats that serialize Web Links and their attributes. One serializes links in the same format as used in HTTP the Link header, and the other as a JSON object. It also defines associated media types to represent sets of links and the "linkset" relation type that supports discovery of any resource that conveys a set of links as a stand-alone document.

@mnot, please let us know if not OK.

**Comment by mnot** [comment]
WFM.
