### ISSUE TITLE
Scenarios

### ISSUE THREAD

**Issue by philarcher** [ietf-wg-httpapi/linkset#37]
Mark's comments at https://mailarchive.ietf.org/arch/msg/httpapi/gv9uqyD8Fv96P-_ip9LWIiCqALM/ suggest that the scenarios section be renamed use cases. I suggest "Use cases and motivation". This gives some cover to the important info in the 2nd para about why the two serializations are made defined.

Some of the language in the three scenarios is complex and could probably be simplified although if I could see an obvious simplification, I'd suggest it! The first scenario might be simplified by talking about server A and server B but ultimately, since everything is a resource and everything has a URI, the language for the abstract case is inevitably complex. 

An example may possibly be useful.

A manufacturer provides links to information about its products' features and sustainability. Separately, an organization concerned with environmental protection provides links to information about the manufacturer's products. Both parties may be motivated to publish links to and about the other's resources, independent of each other.

**Comment by hvdsomp** [comment]
The proposal is to change the section title "Scenarios" by "Use Cases and Motivation" as suggested by @philarcher. 

@mnot, please let us know if not OK.

**Comment by mnot** [comment]
LGTM
