### ISSUE TITLE
Use example including 'anchor' with a fragment

### ISSUE THREAD

**Issue by richsalz** [ietf-wg-httpapi/linkset#4]
Copied from https://github.com/dret/I-D/issues/116; here's the comments:

From @csarven
I think using one of the examples with an anchor including a fragment can diversify (at least visibly) what's possible - this is of course beside the definition of stating (or referring to RFC 8288) as to what an anchor value may be. So like the copyright example in https://tools.ietf.org/html/rfc8288#section-3.5 which refers to a particular part of the document, the following example is about the correction section in the document made by an author:

```
 {"href":"http://authors.example.net/johndoe",
  "anchor":"http://example.org/article?id=10.1371/journal.pone.0167475#amendment-0",
  "rel":["author"],"type":"application/rdf+xml"}
```

(or whatever example is more clear using #)

From @dret
sorry for leaving this open for so long. if you think this is somehow is essential, could you maybe explain why? otherwise we think that of course this can be done, but we're not quite sure why would have to point it out specifically.

From @csarven
As said, using diverse examples can (indirectly) help the reader. It is an editorial call.

From @dret 
i'll leave it up to @hvdsomp to add examples if he feels the need. if not, let's close this one. it is the last open issue! yay!

**Comment by hvdsomp** [comment]
Proposal to address with [this change](https://github.com/hvdsomp/linkset/commit/e9778c193eb92959ab2007c0402237ff52282ce4#diff-0f2ace1dd5f7767f18c52178456e137a3ac46b1c03496edd45dfea4e39f4f79f)

**Comment by hvdsomp** [comment]
hi @richsalz @csarven, I think we addressed this issue, so probably it can be closed.
