### ISSUE TITLE
Relationship to HAL?

### ISSUE THREAD

**Issue by azaroth42** [ietf-wg-httpapi/linkset#49]
[HAL](https://datatracker.ietf.org/doc/html/draft-kelly-json-hal) (Hypertext Application Language) did not make it through the IETF process to become a full RFC, but has many similarities in scope and representation. It also has a reasonably well implemented toolchain, and is pretty easy to embed in other JSON / JSON-LD documentation systems.

Consider: https://github.com/linked-art/linked.art/issues/412#issuecomment-909367374 
Which could also pretty easily be an embedded linkset.

This issue can be closed without action if this is thought not to be in scope, in particular due to the status, but thought it worth consideration at this stage for linkset.

**Comment by hvdsomp** [comment]
This was addressed in 2016/2017 (!) in [https://github.com/dret/I-D/issues/54](https://github.com/dret/I-D/issues/54) and [https://github.com/dret/I-D/issues/48](https://github.com/dret/I-D/issues/48)

**Comment by azaroth42** [comment]
Great, thanks! Closing :)
