### ISSUE TITLE
Relation with application/link-format from RFC6690

### ISSUE THREAD

**Issue by hvdsomp** [ietf-wg-httpapi/linkset#6]
In the mail thread discussing the perceived overlap between application/linkset defined in the I-D and application/link-format defined in RFC6690, @richsalz suggests [to add some wording to clarify the distinction between both](https://mailarchive.ietf.org/arch/msg/httpapi/-3CSpAZcKSqrnT6QlJTEQASqhxE/).

**Comment by hvdsomp** [comment]
Proposal to address with [this change](https://github.com/hvdsomp/linkset/commit/33a621d203ecaa06533f5bc540cc38a1b9bbaa8e#diff-0f2ace1dd5f7767f18c52178456e137a3ac46b1c03496edd45dfea4e39f4f79f)

**Comment by hvdsomp** [comment]
hi @richsalz, I think we addressed this issue, so probably it can be closed.

**Comment by richsalz** [comment]
I'll close this one.  I invited you to be an admin on this repo so you can close the others ;)
