### ISSUE TITLE
References to JSON-LD

### ISSUE THREAD

**Issue by dret** [ietf-wg-httpapi/linkset#65]
This is editorial. Currently it seems when referencing JSON-LD there's a mix of bibliographic references and link-style references (`<xref>` and `<eref>`). If that is intentional that's fine, but it feels like using only one type of reference would be more coherent?

**Comment by hvdsomp** [comment]
Changed the reference in https://github.com/ietf-wg-httpapi/linkset/commit/dd43034f9a4b797309229a8835d58acd31534730
