### ISSUE TITLE
need to define extensibility model for the JSON media type

### ISSUE THREAD

**Issue by reschke** [ietf-wg-httpapi/linkset#8]
Such as "must-understand" or "ignore-extensions".

**Comment by dret** [comment]
thanks for the valuable input, @reschke. i assuming you'd like to see something along the lines of what atom does, right? https://tools.ietf.org/html/rfc4287#section-6

**Comment by dret** [comment]
thanks again for the input, @reschke. this is now addressed in https://datatracker.ietf.org/doc/html/draft-ietf-httpapi-linkset-01#section-4.2.5, please let us know if that resolves the issue for you.

**Comment by reschke** [comment]
ok...

> Extensions based on the  JSON syntax MUST NOT be used, and MUST be ignored when found in a JSON linkset document.

Can you clarify what "based on the JSON syntax" means?

I get that the ext. model is supposed to match RFC 8288. That allows extension parameters, right? So if a link header field uses the extension param "foo", what does that mean for the JSON syntax?

**Comment by dret** [comment]
On 2021-06-01 12:04, Julian Reschke wrote:
> ok...
> 
>     Extensions based on the JSON syntax MUST NOT be used, and MUST be
>     ignored when found in a JSON linkset document.
> 
> Can you clarify what "based on the JSON syntax" means?

it's a bit tricky. there is the RFC 8288 extension model and that one is 
reflected in the JSON syntax. so extensions *to that model* are handled 
just fine. what we want to avoid is people not following that model (and 
the way it gets reflected in the JSON syntax) and simply extending the 
JSON syntax.

in case that explanation is good enough, is there a better way to 
explain it? that's why it says "based on the JSON syntax" right now.

> I get that the ext. model is supposed to match RFC 8288. That allows 
> extension parameters, right? So if a link header field uses the 
> extension param "foo", what does that mean for the JSON syntax?

it will show up as explained in 
https://datatracker.ietf.org/doc/html/draft-ietf-httpapi-linkset#section-4.2.4.3, 
meaning that "foo" will show up as defined by the JSON model. what you 
cannot do is simply throw in a "foo" somewhere in the JSON *without* 
following the rules of 
https://datatracker.ietf.org/doc/html/draft-ietf-httpapi-linkset#section-4.2.4.3

**Comment by reschke** [comment]
I think it would be good if the examples in 4.2.3 and 4.2.4 also showed the linkapplication/linkset variant. Furthermore, wouldn't it be better if 6.1 and 6.2 showed the same set of links, just in different formats?

**Comment by dret** [comment]
thanks for the suggestions, @reschke. @hvdsomp updated some examples and we have new TXT/HTML versions for -02. please et us know what you think or close the issue if you're ok with the updates. thanks.

**Comment by hvdsomp** [comment]
I [revised the Examples Section 6](https://github.com/ietf-wg-httpapi/linkset/commit/2bee3e8013df15bb4a8d01cc3f950e04e26e40d9#diff-78ac3483eb070a5e13b365b9e882859464ff08edc202a7fff9a144388cd78c69) to work with a single, uniform, example.

**Comment by reschke** [comment]
4.2.5. JSON Extensibility says:

> The extensibility of the JSON document format for representing a set of links is restricted to the extensibility provided by [RFC8288]. The Web linking model provides for the use of extension target attributes as discussed in Section 4.2.4.3. Extensions based on the JSON syntax MUST NOT be used, and MUST be ignored when found in a JSON linkset document.

but 4.2.1. Set of Links has:

> If necessary, the "linkset" member MAY contain information in addition to link context objects, in which case that information MUST NOT change the semantics of the links provided by those link context objects.

**Comment by dret** [comment]
the discussion so far has focused on the model described in 4.2.5 (disallowing JSON-based extensions), and it seems that the language in 4.2.1 is a relic of earlier ideas. the proposal is to remove that paragraph from section 4.2.1.

**Comment by dret** [comment]
@reschke, can you please let us know if the proposed solution would resolve this issue for you? thanks!

**Comment by reschke** [comment]
Removing 4.2.1 would be good, yes.

**Comment by hvdsomp** [comment]
Addressed with https://github.com/ietf-wg-httpapi/linkset/commit/03627d769ac4909dd807ff1b3a5b094f2fff20ec
