### ISSUE TITLE
"profile" attribute for link set media types

### ISSUE THREAD

**Issue by hvdsomp** [ietf-wg-httpapi/linkset#9]
It would be useful to define a "profile" attribute for both media types defined in the I-D. Profiles could, for example, be used to express a constraint on the link relation types that are used in a link set. As a concrete example, [TimeMaps](https://www.rfc-editor.org/rfc/rfc7089.html#section-5) from the Memento protocol ([RFC7089](https://www.rfc-editor.org/rfc/rfc7089.html)) could be expressed as link sets. A profile attribute would allow indicating to clients that a particular link set is actually a Memento TimeMap.

**Comment by dret** [comment]
for context: this issue would add a profile media type parameter as defined here: https://datatracker.ietf.org/doc/html/rfc6906#section-3.1

**Comment by hvdsomp** [comment]
I made [changes to the I-D](https://github.com/ietf-wg-httpapi/linkset/commit/174a5299f1dfad0761026da04c67eb0875b78521#diff-78ac3483eb070a5e13b365b9e882859464ff08edc202a7fff9a144388cd78c69) to describe the use of the "profile" attribute for the link set media types.

**Comment by dret** [comment]
On 2021-06-01 12:26, Herbert Van de Sompel wrote:
> I made changes to the I-D 
> <https://github.com/ietf-wg-httpapi/linkset/commit/174a5299f1dfad0761026da04c67eb0875b78521#diff-78ac3483eb070a5e13b365b9e882859464ff08edc202a7fff9a144388cd78c69> 
> to describe the use of the "profile" attribute for the link set media types.

that looks great, thanks. as one minor tweak i'd rather say that profile 
URIs "MAY" be registered, and not "SHOULD" be. the registry has seen 
pretty much no usage so far, and while i think it's great to mention it, 
it's perfectly ok to use profile URIs without registering them.

**Comment by hvdsomp** [comment]
Agreed. I made the change.
